name: work4
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1
enableSuperMixins: true
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/waifu.jpg
    - images/top.jpg
    - images/person.jpg
    - images/desk.png
    - images/desks.png
    - images/dresser.png
    - images/dressers.png
    - images/sofa.png
    - images/sofad.png
    - images/sofas.png
    - images/wardrobe.png
    - images/foto1.jpg
    - images/foto2.jpg
    - images/foto3.jpg
    - images/foto4.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Courgette
       fonts:
         - asset: fonts/Courgette-Regular.ttf

     - family: Lobster
       fonts:
         - asset: fonts/Lobster-Regular.ttf

     - family: LobsterTwo
       fonts:
          - asset: fonts/LobsterTwo-Regular.ttf
          - asset: fonts/LobsterTwo-Bold.ttf
          - asset: fonts/LobsterTwo-BoldItalic.ttf
          - asset: fonts/LobsterTwo-Italic.ttf
     - family: Merienda
       fonts:
          - asset: fonts/Merienda-Regular.ttf
          - asset: fonts/Merienda-Bold.ttf



     - family: Monoton
       fonts:
          - asset: fonts/Monoton-Regular.ttf
     - family: Merriweather
       fonts:
          - asset: fonts/Merriweather-Regular.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
